# Generated by Django 6.0.4 on 2026-05-03 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(max_length=200)),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('drug_class', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('how_to_take', models.TextField()),
                ('side_effects', models.TextField()),
                ('missed_dose_instructions', models.TextField()),
                ('pill_color', models.CharField(default='#2A9090,#1A6B6B', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('once_daily', 'Once Daily'), ('twice_daily', 'Twice Daily'), ('three_daily', 'Three Times Daily'), ('weekly', 'Weekly')], default='once_daily', max_length=20)),
                ('scheduled_time_1', models.TimeField()),
                ('scheduled_time_2', models.TimeField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('supply_days', models.IntegerField(default=30)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_datetime', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_method', models.CharField(blank=True, choices=[('sms', 'SMS'), ('voice', 'Voice'), ('app', 'App'), ('manual', 'Manual')], max_length=10)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('missed', 'Missed'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('escalated', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_logs', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_logs', to='medications.medicationschedule')),
            ],
            options={
                'ordering': ['-scheduled_datetime'],
            },
        ),
    ]
